### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by cdalexndr** [act262/GradleTimeTracker#1]
Gradle 6.5.1:
```
A problem occurred configuring root project 'MyProj'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.micro.gradle:tracker-plugin:1.0.2-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/Alex/.m2/repository/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/Alex/.m2/repository/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/tracker-plugin-1.0.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/tracker-plugin-1.0.2-SNAPSHOT.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by act262** [comment]
> Gradle 6.5.1:
> 
> ```
> A problem occurred configuring root project 'MyProj'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not find io.micro.gradle:tracker-plugin:1.0.2-SNAPSHOT.
>      Searched in the following locations:
>        - file:/C:/Users/Alex/.m2/repository/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/maven-metadata.xml
>        - file:/C:/Users/Alex/.m2/repository/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/tracker-plugin-1.0.2-SNAPSHOT.pom
>        - https://repo.maven.apache.org/maven2/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/maven-metadata.xml
>        - https://repo.maven.apache.org/maven2/io/micro/gradle/tracker-plugin/1.0.2-SNAPSHOT/tracker-plugin-1.0.2-SNAPSHOT.pom
>      Required by:
>          project :
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> ```

U should declare this repository

```
repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
```
